language: ruby
cache: bundler
rvm:
  - 2.6.2
addons:
  chrome: stable
services:
  - postgresql
before_script:
  - psql -c 'create database indyhackers_test;' -U postgres
  - cp config/database.yml.travis config/database.yml

script:
  - bundle exec rake --trace db:setup
  - bundle exec rake --trace spec
